name: Publish Github Pages

on:
  push:
    branches:
      - main

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest

      - name: build
        run: |
          pnpm install
          pnpm build

      - name: Publish Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
