name: Sync Fork

on:
  schedule:
    - cron: '0 10,22 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.AUTO_SYNC_FORK }}
          owner: daeuniverse
          base: main
          head: main
